version: '3.8'

services:

  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - dev_network

  users_api:
    build:
      context: ./APIS
    ports:
      - "3000:3001"  # Mapeo explícito de puerto 3000
    volumes:
      - ./APIS/EPS:/usr/userAPI
    networks:
      - dev_network

  db_dev:
    build:
      context: .
      dockerfile: Dockerfile.postgres_audit
    container_name: eps_db_dev
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 4GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - infraestructura_eps_db_data:/var/lib/postgresql/data
      - ./pg_logs:/var/log/postgresql
      - ./postgresql_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  infraestructura_eps_db_data:
    driver: local

