

services:

  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - citas_api
      - encuesta_api
      - factura_api
      - farmacia_api
      - paciente_api
      - personal_api
    networks:
      - dev_network

  citas_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.citas
    ports:
      - "3100:3100" 


    environment:
      - DATABASE_URL=postgresql://postgres:12345@db_dev:5432/postgres?schema=citas
    volumes:
      - ./APIS/citas:/citas/citasAPI


    networks:
      - dev_network

  encuesta_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.encuesta
    ports:
      - "3200:3200" 


    environment:
      - DATABASE_URL=postgresql://postgres:12345@db_dev:5432/postgres?schema=encuesta
    volumes:
      - ./APIS/encuesta:/encuesta/encuestaAPI

    networks:
      - dev_network

  factura_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.factura
    ports:
      - "3300:3300" 


    environment:
      - DATABASE_URL=postgresql://postgres:12345@db_dev:5432/postgres?schema=factura
    volumes:
      - ./APIS/factura:/factura/facturaAPI


    networks:
      - dev_network

  farmacia_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.factura
    ports:
      - "3400:3400" 


    environment:
      - DATABASE_URL=postgresql://postgres:12345@db_dev:5432/postgres?schema=farmacia
    volumes:
      - ./APIS/farmacia:/farmacia/farmaciaAPI


    networks:
      - dev_network

  paciente_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.paciente
    ports:
      - "3500:3500" 


    environment:
      - DATABASE_URL=postgresql://postgres:12345@db_dev:5432/postgres?schema=paciente
    volumes:
      - ./APIS/paciente:/paciente/pacienteAPI


    networks:
      - dev_network

  personal_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.personal
    ports:
      - "3600:3600" 


    environment:
      - DATABASE_URL=postgresql://postgres:12345@db_dev:5432/postgres?schema=personal
    volumes:
      - ./APIS/personal:/personal/personalAPI


    networks:
      - dev_network

  db_dev:
    build:
      context: .
      dockerfile: Dockerfile.postgres_audit
    container_name: eps_db_dev
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 4GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - infraestructura_eps_db_data:/var/lib/postgresql/data
      - ./pg_logs:/var/log/postgresql
      - ./postgresql_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  infraestructura_eps_db_data:
    driver: local